# Header-菜单
menu: 
  主页: /
  技术笔记: http://note.youdao.com/noteshare?id=dc99836d9979ff1fc3f41f5b155d7b2e
  我的简历: http://kilig947.gitee.io/resume-kilig
  分类: /categories

# subNav-子导航
subNav:
  github: "https://github.com/Kilig947"
  gitee: "https://gitee.com/kilig947/" # 码云
  #jianshu: "#" #简书
  #cnblog: "#"
  #blog: "#"
  #csdn: "#"
  #rss: "#"
  #zhihu: "#"
  #qq: "img/2434387555.jpg"
  #weixin: "img/weixin_.png"
  #weibo: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "2411123479@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

# 悬停预览图片效果
hover_effect:
  ## `global` 0: Set separately, 1: Enable global 2: Close global
  ## `global` 0: 分开设置, 1: 全局启用, 2: 全局关闭
  global: 1
  # SubNav-导航
  subNav: true

# RSS订阅(关于如何配置启用:https://www.jianshu.com/p/2aaac7a19736)
rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 / 设为 /blog/。
# 新版本已弃用，请在博客根目录文件进行配置
# root: /

# Content

# 文章太长，截断按钮文字(在需要截断的行增加此标记：<!--more-->)
#excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false

# Open link in a new tab | 是否在新窗口打开链接
open_in_new:
  article: true  # 文章链接
  menu: true   # 导航菜单
  subNav: true  # 子菜单

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 0
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /img/alipay.jpg
# 微信二维码图片地址
weixin: /img/weixin.png

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
# 百度统计
baidu_analytics: ''
google_analytics: ''

# 网站图标
favicon: /favicon.ico

# 你的头像url
avatar: /img/head.jpg

# 是否开启分享
share_jia: true

# 评论：1、畅言；2、Disqus；3、Gitment；4、Giteement
# 不需要使用某项，直接设置值为false，或注释掉
# 具体请参考wiki：https://github.com/JoeyBling/hexo-theme-yilia-plus/wiki

#评论
#Valine评论系统(https://valine.js.org)
valine:
 appid: jQ2tNfTASRrkYqR8H32LCDlg-gzGzoHsz #Leancloud应用的appId
 appkey: eu0cABDpYvbH8Q6mDeYrdKEI #Leancloud应用的appKey
 verify: false #验证码
 notify: false #评论回复提醒
 avatar: retro #评论列表头像样式：https://valine.js.org/avatar
 placeholder: #评论框占位符


# 访问量统计功能(不蒜子)
busuanzi:
  enable: true
  site_visit: false  # 站点访问量显示
  article_visit: true  # 文章访问量显示

# 网易云音乐插件
music:
  enable: true
  # 播放器尺寸类型(1：长尺寸、2：短尺寸)
  type: 2
  id: 427015442  # 网易云分享的音乐ID(更换音乐请更改此配置项)
  autoPlay: false   # 是否开启自动播放
  # 提示文本(关闭请设置为false)
  text: '自知者不怨人，知命者不怨天'

# 页面点击小红心
clickLove:
  # (关闭请设置为false)
  enable: true

# GitHub Ribbons(https://github.blog/2008-12-19-github-ribbons/)
github:
  # (关闭请设置为false)
  url: false

# 页脚 Litten(此配置项已弃用)
# 帮助我们让更多人可以更方便使用Hexo，请尽量不要修改此主题配置
pageFooter:
  litten: true

# 开启百度站长平台自动推送(https://ziyuan.baidu.com/linksubmit/index)
baidu_push: false

# 版权声明
# 版权声明type设定：0-关闭版权声明； 1-文章对应的md文件里有copyright: true属性，才有版权声明； 2-所有文章均有版权声明
copyright_type: 2
# 版权声明自定义文本(关闭请设置为false)
copyright_text: 

# 网站成立年份(默认为 2018，若填入年份小于当前年份，则显示为 2018-2019 类似的格式)
#since: 2020

# Progress Bar | 页面加载进度条
Demo: http://github.hubspot.com/pace/docs/welcome/
type: barber-shop|big-counter|bounce|center-atom|center-circle|
      center-radar|center-simple|corner-indicator|flash|flat-top|
      loading-bar|mac-osx|minimal
color: black|blue|green|orange|pink|purple|red|silver|white|yellow|
progressBar:
  enable: true
  type: 'minimal'  # Keep Quotes | 保留引号避免出错(某些type会导致样式重叠排版错误)
  color: blue

# Apple Touch icon 苹果图标(关闭请设置为false)
apple_touch_icon: '/apple-touch-icon-180x180.png'

# Tab Title Change | 标签页标题切换
tab_title_change:
  enable: true
  left_tab_title: 
  return_tab_title: 

# https://github.com/willin/hexo-wordcount
# 是否开启字数统计(关闭请设置enable为false)
# 也可以单独在md文件里Front-matter设置`no_word_count: true`属性，来自定义关闭字数统计
word_count:
  enable: false
  # 只在文章详情显示(不在首页显示)
  only_article_visit: true

# 文字输入特效
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: true
  # 使输入模式丰富多彩
  colorful: true
  # 是否开启摇动
  shake: false

# 飘雪特效
# https://github.com/MlgmXyysd/snow.js
snow: false

# 看板娘动态模型插件
## https://github.com/JoeyBling/live2d-widget.js
live2d:
  # (关闭请设置为false)
  enable: true
  # 模型名称(取值请参考：https://github.com/JoeyBling/hexo-theme-yilia-plus/wiki/live2d%E6%A8%A1%E5%9E%8B%E5%8C%85%E5%B1%95%E7%A4%BA)
  model: miku
  display:
    position: right # 显示位置：left/right(default: 'right')
    width: 246  # 模型的长度(default: 150)
    height: 535 # 模型的高度(default: 300)
    hOffset: -50 # 水平偏移(default: 0)
    vOffset: -90 # 垂直偏移(default: -20)
  mobile:
    show: false # 是否在移动设备上显示(default: true)
    scale: 0.6 # 移动设备上的缩放(default: 0.5)
  react:
    opacity: 0.3 # 模型透明度(default: 0.7)

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  # header: '#D3D1DC'
  header: '#FD6C6C'
  gif:
    # 是否启用左侧边栏动态图效果
    enable: false
    # 自定义背景图路径(默认可以不设置，提供默认背景图)
    # path: /img/biubiubiu.gif
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

# 友情链接
friends:
  Python笔记:  #网站名称
    #网站地址
    url: http://note.youdao.com/noteshare?id=dd9555bfea1bbce0635dbfa45bc8017a
    #网站图片(可忽略不写)
    img: /img/python.png
    #网站简介(可忽略不写)
    description:
  Java笔记:
    url: http://note.youdao.com/noteshare?id=02415beefc50120516205df751586185
    img: /img/java.png
  GitHub:
    url: https://github.com/Kilig947
  码云:
    url: https://gitee.com/kilig947
  # 简书:
  #   url: https://www.jianshu.com/u/02cbf31a043a
  # CSDN:
  #   url: https://blog.csdn.net/qq_30930805

# 关于我
aboutme: 主要涉及技术：<br>Web测试、appium、接口自动化测试、<br>压力测试、渗透测试、开源爱好者<br><br>联系QQ:2411123479<br><br>
